apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db
  labels:
    type: mysql-cm
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    CREATE USER 'user'@'%' IDENTIFIED BY 'password';
    GRANT ALL PRIVILEGES ON mydb.* TO 'user'@'%';
    FLUSH PRIVILEGES;
